[package]
name = "inventory"
version = "0.1.0"
authors = ["Ognyan Genev <ognian.genev@gmail.com>"]
edition = "2021"
rust-version = "1.62.1"

[dependencies]
anyhow = "1.0.66"
regex = "1.7.0"
walkdir = "2.3.2"
