[package]
name = "testnet"
version = "0.1.0"
authors = ["Ognyan Genev <ognian.genev@gmail.com>"]
edition = "2021"

[lib]
name = "testnet"
path = "src/lib.rs"

[[bin]]
name = "testnet"
path = "src/main.rs"

[dependencies]
